### ISSUE TITLE
What is the relationship between SSE & SSF?

### ISSUE THREAD

**Issue by rickwang7712** [duo-labs/sharedsignals#66]
I saw some [articles](https://www.okta.com/blog/2022/08/exploration-of-open-identity-standards/) mentioned SSE([OpenID Shared Signals and Events Framework](https://openid.net/specs/openid-sse-framework-1_0-ID1.html)), I'm wondering what's the relationship between SSE & [SSF](https://openid.net/specs/openid-sharedsignals-framework-1_0.html) ? 
Does SSF replace SSE ?

By the way, the receiver in `example` might failed to build due to  `ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/usr/local/lib/python3.9/site-packages/werkzeug/urls.py)`

Appending `Werkzeug==2.2.2` to `examples/receiver/requirements.txt` helps.

**Comment by ozdemirrulass** [comment]
Hi @rickwang7712,
SSF builds on SSE and it extends the coverage of use cases of SSE in a more systematic way. It does not necessarily replaces it but as I said it covers more use cases and I believe natural replacement process is inevitable.

**Comment by deshmukhrajvardhan** [comment]
It's a rename as SSE is more popularly use for Security Service Edge and server-sent event
https://github.com/duo-labs/sharedsignals/pull/64
